# https://alacritty.org/config-alacritty.html
[general]
live_config_reload = true
import = [ "~/.config/alacritty/tokyo_night.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"
opacity = 1.0

[font]
normal = {family = "Iosevka Term", style = "Light"}
bold = {family = "Iosevka Term", style = "Medium"}
italic = {family = "Iosevka Term", style = "Light Italic"}
size = 13

[selection]
save_to_clipboard = true
