[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[font]
normal = {family = "Iosevka"}
size = 13

[selection]
save_to_clipboard = true
