# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true

[window]
dynamic_padding = true
decorations = "buttonless"
option_as_alt = "OnlyLeft"

[font]
normal = {family = "Input Mono"}
size = 12

[selection]
save_to_clipboard = true
