# https://alacritty.org/config-alacritty.html
[general]
live_config_reload = true
import = [ "~/.local/share/nvim/plugged/tokyonight.nvim/extras/alacritty/tokyonight_moon.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"
opacity = 1.0
blur = false

[font]
normal = {family = "FiraCode Nerd Font", style = "Light"}
bold = {family = "FiraCode Nerd Font", style = "Medium"}
italic = {family = "FiraCode Nerd Font", style = "Light Italic"}
size = 13

[selection]
save_to_clipboard = true
