# https://alacritty.org/config-alacritty.html
[general]
live_config_reload = true
# import = [ "~/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_moon.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"
opacity = 1.0
blur = false

[font]
size = 14
normal.family = "FiraCode Nerd Font"

[selection]
save_to_clipboard = true
