# Config: https://pre-commit.com/#plugins
# Hooks: https://pre-commit.com/#new-hooks
---
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: doctoc
        name: doctoc
        description: Generate or update Table of Contents in markdown files
        types: [markdown]
        language: system
        entry: doctoc --notitle --update-only
      # - id: prettier
      #   name: prettier
      #   description: Format markdown files
      #   types: [markdown]
      #   entry: npx prettier --write --check --prose-wrap always
      #   language: system
      - id: markdownlint-cli2
        name: markdownlint-cli2
        description: Lint markdown files
        language: system
        types: [markdown]
        exclude: "^templates/"
        entry: markdownlint-cli2
      # - id: prettier
      #   name: prettier
      #   description: Format markdown files
      #   types: [json, yaml]
      #   entry: prettier --write --check
      #   language: system
      - id: betterleaks
        name: betterleaks
        description: Detect hardcoded secrets using Betterleaks
        entry: betterleaks git --pre-commit --redact --staged --verbose
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        description: Format Python files
        language: system
        types: [python]
        entry: ruff format
      - id: ruff-check-fix
        name: ruff check --fix
        description: Lint Python files
        language: system
        types: [python]
        entry: ruff check --fix
      - id: shellcheck
        name: shellcheck
        description: Lint shell scripts
        types: [shell]
        language: system
        entry: shellcheck
      - id: hadolint
        name: hadolint
        description: Lint Dockerfiles
        language: system
        types: [dockerfile]
        entry: hadolint
      - id: stylua
        name: stylua
        description: Format lua
        language: system
        types: [lua]
        entry: stylua
      - id: luacheck
        name: luacheck
        description: Lint Lua
        language: system
        types: [file, lua]
        entry: luacheck --
      - id: pnpm-lint-fix
        name: pnpm lint:fix
        description: Lint and auto-fix JS/TS files
        language: system
        types_or: [javascript, jsx, ts, tsx]
        entry: pnpm lint:fix
        pass_filenames: false
      - id: pnpm-fmt
        name: pnpm fmt
        description: Format JS/TS files
        language: system
        # types_or: [javascript, jsx, ts, tsx]
        entry: pnpx oxfmt
        pass_filenames: false
      - id: commitizen
        name: commitizen
        description: This hook lints commit messages
        stages: [commit-msg] # run only in git commit-msg lifecycle event
        language: system
        entry: cz check --commit-msg-file
