theme = "base16_default"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
