# config: https://starship.rs/config/
# curl -sS https://starship.rs/install.sh | sh

format = """
$sudo\
$username\
$hostname\
$directory\
$localip\
$shlvl\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$deno\
$golang\
$helm\
$nodejs\
$python\
$rust\
$terraform\
$aws\
$gcloud\
$azure\
$memory_usage\
$battery\
$time\
$status\
$container\
$jobs\
$line_break\
$character"""

add_newline = true

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[shlvl]
disabled = false
symbol = "shlvl:"

[battery]
full_symbol = "= "
charging_symbol = "+ "
discharging_symbol = "- "

[[battery.display]]
threshold = 100

[container]
format = " [$symbol \\[$name\\]]($style) "

[jobs]
symbol = "+"

[time]
format = ' [$time]($style) '
use_12hr = true
disabled = false

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[deno]
symbol = "deno "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "
disabled = false
threshold = 0
format = ' \[$symbol[$ram( | $swap)]($style)\] '

[package]
symbol = "pkg "

[python]
symbol = "py "

[rust]
symbol = "rs "

[sudo]
symbol = "sudo "

[terraform]
symbol = "terraform "
