services:
  dev:
    image: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.aws:/root/.aws
      - ${HOME}/.vim:/root/.vim
      - ${HOME}/.config:/root/.config
      - ${HOME}/.kube:/root/.kube
      - ${HOME}/.docker:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/root/workspace
    environment:
      - TERM
      - PS1
    working_dir: "/root/workspace"
