# herdr server reload-config
onboarding = false

[theme]
name = "tokyo-night-day"
auto_switch = true

[keys]
next_tab = ["prefix+n", "ctrl+alt+]"]
goto = ["prefix+ctrl+w"]
cycle_pane_next = "prefix+ctrl+o"
split_vertical = "prefix+backslash"
next_agent = "alt+]"
previous_agent = "alt+["
focus_agent = "alt+1..9"
next_workspace = ["prefix+ctrl+n"]
previous_workspace = ["prefix+ctrl+p"]

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "cd ~/.dotfiles && pi --model glean"
description = "Pi with Glean"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "nvim -c Projects"
description = "Projects"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+ctrl+f"
type = "popup"
command = "fzf-herdr-project"
description = "Fuzzy-find projects"
width = "80%"
height = "80%"

[ui]
show_agent_labels_on_pane_borders = false

[ui.toast]
delivery = "herdr"
