onboarding = false

[theme]
name = "tokyo-night-day"
auto_switch = true

[keys]
next_tab = ["prefix+n", "ctrl+alt+]"]
goto = ["prefix+ctrl+w"]
cycle_pane_next = "prefix+ctrl+o"
split_vertical = "prefix+backslash"
next_agent = "alt+]"
previous_agent = "alt+["
next_workspace = ["prefix+ctrl+n"]
previous_workspace = ["prefix+ctrl+p"]

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "pi --model glean"
description = "Pi with Glean"
width = "80%"
height = "80%"

[ui]
show_agent_labels_on_pane_borders = false

[ui.toast]
delivery = "herdr"
