vim.pack.add({ "https://github.com/nvim-mini/mini.nvim" })

require("mini.bracketed").setup()
require("mini.diff").setup()
require("mini.git").setup()
require("mini.icons").setup()
require("mini.misc").setup_auto_root()
require("mini.move").setup()
require("mini.splitjoin").setup()
require("mini.surround").setup()
