require("config.ui")
require("config.globals")
require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.colorscheme")
require("config.diagnostics")
require("config.filetypes")
