vim.keymap.set("n", "<leader>ll", "<cmd>Lazy<cr>")
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("c", "<c-p>", "<up>")
vim.keymap.set("c", "<c-n>", "<down>")
vim.keymap.set("t", "<esc><esc>", "<c-\\><c-n>")
