vim.keymap.set("n", "<leader>ll", vim.cmd.Lazy, { desc = "[L]azy" })
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("c", "<c-p>", "<up>")
vim.keymap.set("c", "<c-n>", "<down>")
