vim.g.editorconfig = true
vim.g.netrw_keepdir = 0
vim.opt.backspace = "indent,eol,start"
vim.opt.belloff = "all"
vim.opt.breakindent = true
vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 1
vim.opt.complete = ".,w,b,u,t"
vim.opt.completeopt = { "menu", "menuone", "popup", "fuzzy", "noselect" }
vim.opt.cursorline = false
vim.opt.expandtab = true
vim.opt.foldenable = false
vim.opt.grepformat:append({ "%f:%l:%c:%m", "%f:%l:%m" })
vim.opt.guifont = { "Iosevka Nerd Font Mono" }
vim.opt.hidden = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.inccommand = "split"
vim.opt.incsearch = true
vim.opt.infercase = true
vim.opt.iskeyword = "@,48-57,_,192-255,-,#"
vim.opt.laststatus = 2
vim.opt.list = true
vim.opt.listchars = "tab:│⋅,trail:⋅,nbsp:␣"
vim.opt.modeline = true
vim.opt.modelines = 5
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.ruler = false
vim.opt.scrolloff = 10
vim.opt.shortmess = "FICcW"
vim.opt.showmode = false
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smarttab = true
vim.opt.swapfile = false
vim.opt.title = true
vim.opt.titlestring = "%F"
vim.opt.ttimeout = true
vim.opt.ttimeoutlen = 50
vim.opt.ttyfast = true
vim.opt.undofile = true
vim.opt.wildignorecase = true
vim.opt.wildmenu = true
vim.opt.wildoptions = { "pum", "fuzzy" }
vim.opt.winborder = "rounded"
vim.opt.wrap = false
vim.opt.wrapscan = false
