; https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md
version = 1

[*]
cache-type-k = q8_0
cache-type-v = q8_0
cont-batching = true
flash-attn = true
n-gpu-layers = all
parallel = 1
presence-penalty = 1.5
repeat-penalty = 1.0

[unsloth/Qwen3.5-9B-MTP-GGUF:Q4_K_M]
hf-repo = unsloth/Qwen3.5-9B-MTP-GGUF:Q4_K_M
spec-type = draft-mtp
spec-draft-n-max = 2

[unsloth/Qwen3.5-4B-MTP-GGUF:Q4_K_M]
hf-repo = unsloth/Qwen3.5-4B-MTP-GGUF:Q4_K_M
spec-type = draft-mtp
spec-draft-n-max = 2
